#!/usr/bin/env ruby

require "RPi_Emulator_Manager"

def cmd_list
  type = ARGV[1]
  case type
  when 'os'
    @data_manager.os.each do |id,o|
      puts "#{id}\n\t#{o.name} #{o.details}\n\tFirmware: #{o.firmware_id}\n\tHardware available: #{o.hardware_ids.join(", ")}\n\n"
    end
  when 'hardware', 'hw'
    @data_manager.hardware.each do |id,hw|
      puts "#{id}\n\t#{hw.name}\n\tqemu-system-#{hw.qemu_arch}\n\n"
    end
  when 'image', 'img'
    @data_manager.images.each do |id,img|
      puts "#{id}\n\t#{img.name}\n\tOperating System: #{img.os_id}\n\tHardware: #{img.hardware_id}\n\n"
    end
  when 'firmware', 'fw'
    @data_manager.firmware.each do |id,f|
      puts "#{id}\n\t#{f.dl_link}\n\n"
    end
  else
    raise ArgumentError.new "no resource for '#{ARGV[1]}' exists"
  end
end

def cmd_new
  type = ARGV[1]
  case type
  when 'os'
    required_args(7)
    id = ARGV[2]
    name = ARGV[3]
    details = ARGV[4]
    firmware_id = ARGV[5]
    dl_link = ARGV[6]
    hw_ids = ARGV[7..-1]

    @data_manager.create_os id, name, details, firmware_id, hw_ids, dl_link
  when 'hardware', 'hw'
    required_args(6,6)
    id = ARGV[2]
    name = ARGV[3]
    qemu_arch = ARGV[4]
    qemu_args = ARGV[5]

    @data_manager.create_hardware(id, name, qemu_arch, qemu_args)
  when 'image', 'img'
    required_args(5,5)
    name = ARGV[2]
    hardware = ARGV[3]
    os = ARGV[4]

    puts 'Downloading image. This may take a few minutes...'
    @data_manager.create_image name, hardware, os
  else
    raise ArgumentError.new "no resource for '#{ARGV[1]}' exists"
  end
end

def cmd_rm
  type = ARGV[1]
  id = ARGV[2]

  case type
  when 'os'
    raise ArgumentError.new "no operating system found for id '#{id}'" unless @data_manager.has_resource? :os, id.to_sym
    @data_manager.delete_resource(:os, id)
  when 'hardware', 'hw'
    raise ArgumentError.new "no hardware found for id '#{id}'" unless @data_manager.has_resource? :hardware, id.to_sym
    @data_manager.delete_resource(:hardware, id)
  when 'image', 'img'
    raise ArgumentError.new "no image found for id '#{id}'" unless @data_manager.has_resource? :image, id.to_sym
    @data_manager.delete_resource(:image, id)
  when 'firmware', 'fw'
    raise ArgumentError.new "no firmware found for id '#{id}'" unless @data_manager.has_resource? :firmware, id.to_sym
    @data_manager.delete_resource(:firmware, id)
  else
    raise ArgumentError.new "no resource for '#{ARGV[1]}' exists"
  end
end

def cmd_run(img_id = ARGV[1])
  cmd = @data_manager.get_qemu_cmd(img_id)
  puts cmd
  exec(cmd)
end

def cmd_rl
  raise ArgumentError.new 'no last image run data' if @data_manager.last_image.nil?
  cmd_run @data_manager.last_image
end

def cmd_update
  @data_manager.update_defaults
end

def cmd_help
  cmd = File.basename($PROGRAM_NAME)
  puts <<-EOF
#{cmd}

Commands:
  rl:
    #{cmd} rl

    Run the last run image.
  run:
    #{cmd} run [image_id]

    Run an image in QEMU.

  new:
    #{cmd} new [resource] [...]

    Create a new instance of a resource.

  rm:
    #{cmd} rm [resource] [id]

    Delete an existing resource. Only works on user created resources.

  list, ls:
    #{cmd} list [resource]

    List all items under a resource.

  update:
    #{cmd} update

    Replace all default installed resources with the latest defaults. All user
    created resources are left unchanged.

  help, h:
    #{cmd} help

    This message.

Resources:
  os:
    Operating systems.

  hardware,hw:
    Hardware devices.

  image,img:
    Specific images.

  firmware,fw:
    Firmware versions.

  EOF
end

def required_args(min = nil, max = nil)
  if !min.nil? && ARGV.size < min
    raise ArgumentError.new "missing required argument(s)"
  end
  if !max.nil? && ARGV.size > max
    raise ArgumentError.new "more arguments than expected"
  end
end

@data_manager = DataManager.new
command = ARGV.first

begin

case command
when 'rl'
  required_args(1,1)
  cmd_rl
when 'run'
  required_args(2,2)
  cmd_run
when 'new'
  # required_args checks in cmd_new
  cmd_new
when 'rm'
  required_args(3,3)
  cmd_rm
when 'list', 'ls'
  required_args(2,2)
  cmd_list
when 'update'
  required_args(1,1)
  cmd_update
when 'help', 'h'
  cmd_help
else
  raise ArgumentError.new "unknown command '#{command}'"
end

rescue => e
  if e.is_a?  ArgumentError
    puts e.message
  else
    puts e.full_message
  end
  exit 1
end